In [1]:
import numpy as np

In [2]:
#numpy  = numerical python

In [5]:
my_list = [1,2,3,4]

In [6]:
print(my_list)

[1, 2, 3, 4]


In [7]:
my_list2 = my_list *2

In [8]:
print(my_list2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [9]:
array = np.array([1,2,3,4])

In [13]:
array  = array*2

In [14]:
print(array)

[2 4 6 8]


In [15]:
#Multidimentional

In [23]:
array = np.array('A')

In [24]:
print(array.ndim)
print(array)

0
A


In [25]:
array2 = np.array(['A','B','C','D'])

In [27]:
print(array2.ndim) # one dimentional
print(array2)

1
['A' 'B' 'C' 'D']


In [47]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', '']]])

In [48]:
print(array.ndim)

3


In [49]:
array.shape #ndim, row,column, 

(3, 3, 3)

In [60]:
print(array[0,0,1])


B


In [62]:
print(array[1,1,1])

N


In [63]:
word = array[0,0,0] + array[2,0,0] + array[2,0,0]

In [64]:
word

'ASS'

In [65]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [66]:
#array[start:end:step]

In [78]:
print(array[1:2:1])

[[5 6 7 8]]


In [91]:
print(array[0:1:1])

[[1 2 3 4]]


In [95]:
print(array[::2]) # this is row selection

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [98]:
print(array[:,0]) # from 0 to 4th index for the first column

[ 1  5  9 13]


In [107]:
print(array[:,0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [123]:
print(array[:,1:]) #without first column 

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [126]:
print(array[:,::])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [129]:
print(array[0:2,0:2])

[[1 2]
 [5 6]]


In [136]:
print(array[2:,2:]) # sol alt dörtlüyü aldım

[[11 12]
 [15 16]]


In [137]:
#Arithmetic

In [138]:
#scaler arithmetic lineer algebra term

In [150]:
array = np.array([1.01,2.5,3.99])
print(array + 1) # each one ++

[2.01 3.5  4.99]


In [151]:
print(array - 2)
print(array * 2)
print(array ** 3)

[-0.99  0.5   1.99]
[2.02 5.   7.98]
[ 1.030301 15.625    63.521199]


In [152]:
#Vectoral

In [153]:
print(np.sqrt(array)) # each element 

[1.00498756 1.58113883 1.99749844]


In [154]:
print(np.round(array))

[1. 2. 4.]


In [158]:
print(np.pi)

3.141592653589793


In [160]:
radii = array = np.array([1,2,3])

In [161]:
print(np.pi * radii**2)

[ 3.14159265 12.56637061 28.27433388]


In [162]:
#Element wise arithmetic

In [165]:
array1 = np.array([1,2,3])
array2 = np.array([3,4,6])
print(array1*array2)
print(array1+array2)

[ 3  8 18]
[4 6 9]


In [173]:
scores = np.array([91,55,100,73,82,64])
scores[scores < 60] =  0

In [174]:
print(scores)

[ 91   0 100  73  82  64]


In [175]:
#BroadCasting

In [196]:
array1 = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])


In [197]:
array2 = np.array([[2],[3],[4],[5]])

In [198]:
array2.shape

(4, 1)

In [199]:
print(array1 * array2)

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]
 [65 70 75 80]]


In [200]:
arrayx = np.array([[1,2,3,4,5,6,7,8,9,10]])

In [201]:
arrayy = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

In [205]:
print(arrayx.shape)
arrayy.shape

(1, 10)


(10, 1)

In [206]:
array  = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [209]:
print(np.sum(array))

55


In [210]:
print(np.mean(array))

5.5


In [211]:
print(np.median(array))

5.5


In [212]:
print(np.std(array))

2.8722813232690143


In [213]:
print(np.var(array))

8.25


In [214]:
print(np.min(array))

1


In [215]:
print(np.max(array))

10


In [220]:
print(np.argmin(array)) # min value which index ? 

0


In [221]:
array  = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [224]:
print(np.sum(array,axis=1))

[15 40]


In [225]:
print(np.sum(array,axis=0))

[ 7  9 11 13 15]


In [226]:
#Filtering  Refers to the process of selecting elemeent from an array that match a given condition

In [227]:
ages = np.array([[21,17,19,20,16,30,18,65],
               [39,22,15,99,18,19,20,21]])

In [230]:
teenagers = ages[ages<18] # return new array

In [231]:
print(teenagers)

[17 16 15]


In [238]:
adults = ages[(ages<18) | (ages<65)]

In [239]:
print(adults)

[21 17 19 20 16 30 18 39 22 15 18 19 20 21]


In [240]:
seniors = ages[ages>=65]

In [241]:
seniors

array([65, 99])

In [242]:
even = ages[ages % 2 ==0]

In [243]:
even

array([20, 16, 30, 18, 22, 18, 20])

In [244]:
#filter

In [252]:
adults = np.where(ages>=18,ages,-1) # buradaki son index ne ile değişim yapaağımı gösterecek

In [253]:
adults

array([[21, -1, 19, 20, -1, 30, 18, 65],
       [39, 22, -1, 99, 18, 19, 20, 21]])

In [254]:
adults = np.where(ages>=18,ages,12)
print(adults)

[[21 12 19 20 12 30 18 65]
 [39 22 12 99 18 19 20 21]]


In [255]:
#Random

In [295]:
rng = np.random.default_rng()

In [296]:
print(rng.integers(1,7,10))

[1 1 2 4 3 1 3 1 3 3]


In [297]:
print(rng.integers(low=1,high=101,size =(3,2))) # size =  kaç tane lazım 

[[30 69]
 [43 81]
 [71 57]]


In [298]:
print(np.random.uniform(low = 10,high=15,size=(3,2)))

[[12.65312116 12.55159936]
 [10.32124256 14.1999082 ]
 [11.29054007 14.1425016 ]]


In [302]:
array = np.array([1,2,3,4,5])

In [303]:
rng.shuffle(array)

In [304]:
print(array)

[2 1 3 4 5]


In [308]:
friuts = np.array(["apple","orange","banana","coconut"])

In [309]:
friuts = rng.choice(friuts)

In [311]:
print(friuts)

apple
