In [1]:
import numpy as np

In [2]:
#numpy  = numerical python

In [5]:
my_list = [1,2,3,4]

In [6]:
print(my_list)

[1, 2, 3, 4]


In [7]:
my_list2 = my_list *2

In [8]:
print(my_list2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [9]:
array = np.array([1,2,3,4])

In [13]:
array  = array*2

In [14]:
print(array)

[2 4 6 8]


In [15]:
#Multidimentional

In [23]:
array = np.array('A')

In [24]:
print(array.ndim)
print(array)

0
A


In [25]:
array2 = np.array(['A','B','C','D'])

In [27]:
print(array2.ndim) # one dimentional
print(array2)

1
['A' 'B' 'C' 'D']


In [47]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', '']]])

In [48]:
print(array.ndim)

3


In [49]:
array.shape #ndim, row,column, 

(3, 3, 3)

In [60]:
print(array[0,0,1])


B


In [62]:
print(array[1,1,1])

N


In [63]:
word = array[0,0,0] + array[2,0,0] + array[2,0,0]

In [64]:
word

'ASS'

In [65]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [66]:
#array[start:end:step]

In [78]:
print(array[1:2:1])

[[5 6 7 8]]


In [91]:
print(array[0:1:1])

[[1 2 3 4]]


In [95]:
print(array[::2]) # this is row selection

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [98]:
print(array[:,0]) # from 0 to 4th index for the first column

[ 1  5  9 13]


In [107]:
print(array[:,0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [123]:
print(array[:,1:]) #without first column 

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [126]:
print(array[:,::])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [129]:
print(array[0:2,0:2])

[[1 2]
 [5 6]]


In [131]:
print(array[2:,0:2]) # sol alt dörtlüyü aldım

[[ 9 10]
 [13 14]]
