In [2]:
import numpy as np

In [3]:
#Arrays

In [5]:
my_list = [10,20,30,40 ]
type(my_list)

list

In [7]:
my_numpy_array = np.array(my_list)

In [8]:
type(my_numpy_array)

numpy.ndarray

In [12]:
my_numpy_array.max()

np.int64(40)

In [13]:
my_numpy_array.mean()

np.float64(25.0)

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.random.random(5)

array([0.83180913, 0.72269895, 0.22254517, 0.49334635, 0.27550097])

In [18]:
#array arithmetic

In [39]:
my_list1 = [1,2,45]

In [40]:
my_list2 = [2,112,12 ]

In [41]:
my_list1 + my_list2

[1, 2, 45, 2, 112, 12]

In [42]:
myNpArray1 = np.array(my_list1)

In [43]:
myNpArray2 = np.array(my_list2)

In [44]:
myNpArray1 +  myNpArray2 #Adding the values each rows

array([  3, 114,  57])

In [45]:
myNpArray1 * myNpArray2 

array([  2, 224, 540])

In [46]:
myNpArray1 *4

array([  4,   8, 180])

In [47]:
myNpArray1 +54

array([55, 56, 99])

In [48]:
other_array = np.array([10,20,30,40,50])

In [49]:
other_array.min()

np.int64(10)

In [50]:
other_array.sum()

np.int64(150)

In [51]:
#Arrange & indexing

In [52]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [57]:
np_array = np.arange(0,10)

In [58]:
np_array[0]

np.int64(0)

In [59]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np_array[0]

np.int64(0)

In [61]:
np_array[-1]

np.int64(9)

In [62]:
np_array[1:4:]

array([1, 2, 3])

In [63]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [64]:
np_array[2:6:2]

array([2, 4])

In [65]:
#Random

In [66]:
np.random.randn(4)

array([ 1.42677322,  0.01547755,  0.16959419, -1.4074168 ])

In [67]:
np.random.randn(4,4)

array([[-1.22625278, -0.60027776, -0.0707788 ,  0.29124295],
       [ 0.73922447, -0.05909594,  0.7169306 ,  2.71782273],
       [ 0.06641011,  0.69261986, -0.23020452,  0.78352901],
       [ 2.34379905,  0.23945544,  0.49783534,  0.62021331]])

In [ ]:
np.random.randint(1)