In [1]:
import numpy as np

In [4]:
new_Array = np.random.randint(1,100,20)

In [5]:
new_Array

array([21, 75,  9,  4, 96, 12,  6, 97, 66, 11, 93, 81, 28, 85,  3, 89, 53,
       10, 87, 49], dtype=int32)

In [7]:
new_Array >12

array([ True,  True, False, False,  True, False, False,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True, False,
        True,  True])

In [10]:
new_Array [new_Array >12]

array([21, 75, 96, 97, 66, 93, 81, 28, 85, 89, 53, 87, 49], dtype=int32)

In [11]:
#Traspose

In [12]:
x = np.array([[10,20],[20,30],[30,40]])

In [13]:
x

array([[10, 20],
       [20, 30],
       [30, 40]])

In [14]:
x.shape

(3, 2)

In [18]:
x.transpose().shape

(2, 3)

In [17]:
x.shape

(3, 2)

In [19]:
x.T

array([[10, 20, 30],
       [20, 30, 40]])

In [35]:
randomx  = np.random.random((6,1))

In [36]:
randomx

array([[0.26941538],
       [0.0117735 ],
       [0.77714661],
       [0.75158658],
       [0.23444152],
       [0.07928888]])

In [39]:
randomx.reshape(2,3)

array([[0.26941538, 0.0117735 , 0.77714661],
       [0.75158658, 0.23444152, 0.07928888]])

In [40]:
randomx.reshape(3,2)

array([[0.26941538, 0.0117735 ],
       [0.77714661, 0.75158658],
       [0.23444152, 0.07928888]])

In [41]:
# z-score

In [42]:
data  = np.array([10,12,13,15,18,25,100,105])

In [44]:
data.mean()

np.float64(37.25)

In [45]:
#outlier

In [46]:
mean = np.mean(data)

In [47]:
mean

np.float64(37.25)

In [50]:
data.sum() / len(data)

np.float64(37.25)

In [51]:
std = np.std(data)

In [52]:
std

np.float64(37.9333296719389)

In [53]:
z_score =  (data- mean) / std

In [54]:
z_score

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [57]:
data[z_score > 1] #outliers

array([100, 105])

In [58]:
#Math equations

In [59]:
#2x + 3y = 8 and 5x + 7y = 19

In [61]:
A = np.array([[2,3],[5,7]])

In [66]:
B = np.array([128,19])

In [67]:
sol = np.linalg.solve(A,B)

In [68]:
sol

array([-839.,  602.])

In [69]:
np.array([True, 1, 2]) + np.array([3, 4, False])


array([4, 5, 2])

In [1]:
# NumPy Kapsamlı Rehber: Temelden İleri Seviyeye Örnekler
# Bu script, NumPy'nin temelinden ileri seviyesine kadar en çok kullanılan özelliklerini kapsar.
# Her bölümde detaylı açıklamalar yorum satırları olarak eklenmiştir.
# Veri bilimi perspektifinden örnekler odaklanılmıştır: Veri manipülasyonu, analiz, makine öğrenmesi hazırlığı.
# Script'i çalıştırarak çıktıları görebilirsiniz. Jupyter Notebook'ta denemenizi öneririm.
# Önce NumPy'yi import edelim.
import numpy as np

# Bölüm 1: Temel Array Oluşturma
# NumPy array'ler, Python listelerinden daha hızlı ve verimli. Çok boyutlu olabilirler.
# Neden önemli? Veri setlerini temsil etmek için temel yapı.

# 1.1 Basit 1D Array Oluşturma
# np.array() ile bir liste array'e dönüştürülür.
arr = np.array([1, 2, 3, 4, 5])  # Integer array
print("1D Array:", arr)  # Çıktı: [1 2 3 4 5]

# 1.2 2D Array (Matris) Oluşturma
# İç içe listelerle çok boyutlu array.
arr2d = np.array([[1, 2, 3], [4, 5, 6]])  # 2 satır, 3 sütun
print("2D Array:\n", arr2d)  # Çıktı: [[1 2 3] [4 5 6]]

# 1.3 Sıfır Dolu Array
# np.zeros(): Başlangıç matrisi için kullanılır, veri bilimi: Boş veri seti doldurma.
zeros = np.zeros((2, 3))  # 2x3 sıfır matrisi, dtype=float varsayılan
print("Zeros Array:\n", zeros)  # Çıktı: [[0. 0. 0.] [0. 0. 0.]]

# 1.4 Bir Dolu Array
# np.ones(): Sabit değerlerle doldurma, örneğin normalizasyon için.
ones = np.ones((3, 2), dtype=int)  # 3x2 bir matrisi, integer tipi
print("Ones Array:\n", ones)  # Çıktı: [[1 1] [1 1] [1 1]]

# 1.5 Birim Matris
# np.eye(): Lineer cebirde diagonal matris için, makine öğrenmesi: Kimlik matrisi.
eye = np.eye(3)  # 3x3 birim matris
print("Eye Matrix:\n", eye)  # Çıktı: [[1. 0. 0.] [0. 1. 0.] [0. 0. 1.]]

# 1.6 Aralıklı Sayılar: np.arange()
# Range gibi, ama float destekler. Zaman serisi indeksleri için pratik.
arange = np.arange(0, 10, 2)  # 0'dan 10'a 2'şer adım
print("Arange:", arange)  # Çıktı: [0 2 4 6 8]

# 1.7 Eşit Aralıklı Sayılar: np.linspace()
# Örnekleme için kullanılır, veri görselleştirme: Eşit dağılımlı noktalar.
linspace = np.linspace(0, 1, 5)  # 0-1 arası 5 nokta
print("Linspace:", linspace)  # Çıktı: [0.   0.25 0.5  0.75 1.  ]

# 1.8 Boş Array (Rastgele Değerler)
# np.empty(): Hızlı boş array, ama değerler belirsiz (bellekten kalıntı).
empty = np.empty((2, 2))  # 2x2 boş, değerler rastgele olabilir
print("Empty Array:\n", empty)  # Çıktı: Rastgele değerler

# Bölüm 2: Array Özellikleri
# Array'lerin shape, dtype gibi özelliklerini inceleme. Hataları önlemek için önemli.

# 2.1 Shape: Boyutlar
print("arr Shape:", arr.shape)  # Çıktı: (5,) - 1D, 5 eleman

# 2.2 Dtype: Veri Tipi
print("arr Dtype:", arr.dtype)  # Çıktı: int64 (makineye göre değişir)

# 2.3 Ndim: Boyut Sayısı
print("arr2d Ndim:", arr2d.ndim)  # Çıktı: 2

# 2.4 Size: Toplam Eleman Sayısı
print("arr2d Size:", arr2d.size)  # Çıktı: 6

# 2.5 Tip Dönüştürme
# astype(): Veri bilimi: Float'a çevirmek için (hesaplamalarda hassasiyet).
float_arr = arr.astype(np.float32)
print("Float Array:", float_arr)  # Çıktı: [1. 2. 3. 4. 5.]

# Bölüm 3: İndeksleme ve Slicing
# Veri çekme, filtreleme için temel. Çok boyutlu slicing güçlü.

# 3.1 Tek Eleman Erişimi
print("arr[0]:", arr[0])  # Çıktı: 1

# 3.2 Slicing: Alt Küme
slice_arr = arr[1:4]  # 1'den 4'e kadar (dahil değil)
print("Slice:", slice_arr)  # Çıktı: [2 3 4]

# 3.3 2D İndeksleme
print("arr2d[1, 2]:", arr2d[1, 2])  # 2. satır, 3. sütun: 6

# 3.4 Kolon/Sütun Slicing
col = arr2d[:, 1]  # Tüm satırlar, 2. sütun
print("Column Slice:", col)  # Çıktı: [2 5]

# 3.5 Negatif İndeksleme
print("arr[-1]:", arr[-1])  # Son eleman: 5

# 3.6 Adım Atlamalı Slicing
step_slice = arr[::2]  # Her 2. eleman
print("Step Slice:", step_slice)  # Çıktı: [1 3 5]

# Bölüm 4: Aritmetik İşlemler ve Broadcasting
# Vektörel işlemler: Döngü olmadan hızlı hesap. Veri normalizasyonu için ideal.

# 4.1 Basit Aritmetik
add = arr + 10  # Her elemana 10 ekle
print("Add 10:", add)  # Çıktı: [11 12 13 14 15]

sub = arr - 2
print("Subtract 2:", sub)  # Çıktı: [-1  0  1  2  3]

mul = arr * 3
print("Multiply 3:", mul)  # Çıktı: [ 3  6  9 12 15]

div = arr / 2
print("Divide 2:", div)  # Çıktı: [0.5 1.  1.5 2.  2.5]

# 4.2 Array-Array İşlemleri
arr_sum = arr + np.array([5, 4, 3, 2, 1])
print("Array Sum:", arr_sum)  # Çıktı: [6 6 6 6 6]

# 4.3 Broadcasting: Farklı Boyutları Uyumlu Hale Getir
# 2D array'e 1D ekleme: Her satıra uygula.
broadcast = arr2d + np.array([1, 2, 3])
print("Broadcasting:\n", broadcast)  # Çıktı: [[2 4 6] [5 7 9]]

# 4.4 Güç Alma ve Mod
power = arr ** 2
print("Power 2:", power)  # Çıktı: [ 1  4  9 16 25]

mod = arr % 3
print("Mod 3:", mod)  # Çıktı: [1 2 0 1 2]

# Bölüm 5: Matematiksel ve İstatistiksel Fonksiyonlar
# Veri analizi: Ortalama, varyans vb. Axis ile boyut bazında hesap.

# 5.1 Temel İstatistik
print("Sum:", arr.sum())  # 15
print("Mean:", arr.mean())  # 3.0
print("Median:", np.median(arr))  # 3.0
print("Std Dev:", arr.std())  # Standart sapma: ~1.414
print("Var:", arr.var())  # Varyans: 2.0
print("Min/Max:", arr.min(), arr.max())  # 1 5

# 5.2 Axis Bazında: Sütun/Satır
print("2D Sum Axis=0 (Sütun):", arr2d.sum(axis=0))  # [5 7 9]
print("2D Mean Axis=1 (Satır):", arr2d.mean(axis=1))  # [2. 5.]

# 5.3 Trigonometrik Fonksiyonlar
sin_arr = np.sin(arr)
print("Sin:", sin_arr)  # Sinüs değerleri

# 5.4 Exponential ve Log
exp = np.exp(arr)
print("Exp:", exp)  # e^arr

log = np.log(arr + 1)  # Logaritma (0 önlemek için +1)
print("Log:", log)

# 5.5 Yuvarlama
round_arr = np.round(np.array([1.2, 2.7, 3.5]))
print("Round:", round_arr)  # [1. 3. 4.]

# Bölüm 6: Rastgele Sayılar (np.random)
# Simülasyon, veri üretme, bootstrapping için. Makine öğrenmesi: Random seed ile tekrarlanabilirlik.

# 6.1 Seed Ayarlama (Tekrarlanabilirlik)
np.random.seed(42)  # Aynı sonuçlar için

# 6.2 Uniform Rastgele (0-1 arası)
rand = np.random.rand(3)  # 3 rastgele float
print("Rand:", rand)

# 6.3 Normal Dağılım
randn = np.random.randn(2, 2)  # Standart normal (mean=0, std=1)
print("Randn:\n", randn)

# 6.4 Tamsayı Rastgele
randint = np.random.randint(1, 10, size=(2, 3))  # 1-10 arası, 2x3
print("Randint:\n", randint)

# 6.5 Karıştırma
shuffle_arr = np.array([1,2,3,4,5])
np.random.shuffle(shuffle_arr)
print("Shuffled:", shuffle_arr)

# 6.6 Seçim Yapma
choice = np.random.choice(arr, size=3, replace=False)  # Tekrarsız 3 seçim
print("Choice:", choice)

# Bölüm 7: Lineer Cebir (np.linalg ve Dot)
# Makine öğrenmesi: Regresyon, PCA, matris işlemleri.

# 7.1 Nokta Çarpımı (Dot Product)
dot = np.dot(arr2d, np.array([1, 2, 3]))  # Matris * vektör
print("Dot:", dot)  # [14 32]

# 7.2 Matris Çarpımı (@ operatörü)
mat_mul = arr2d @ np.array([[1], [2], [3]])
print("Matrix Mul:\n", mat_mul)

# 7.3 Matris Tersi
square = np.array([[1, 2], [3, 4]])
inv = np.linalg.inv(square)
print("Inverse:\n", inv)

# 7.4 Özdeğerler ve Özvektörler
eigvals, eigvecs = np.linalg.eig(square)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

# 7.5 SVD (Singular Value Decomposition)
u, s, vh = np.linalg.svd(square)
print("SVD S:", s)

# Bölüm 8: Reshape, Stack, Split ve Concat
# Veri dönüştürme: Makine öğrenmesi input hazırlama.

# 8.1 Reshape: Boyut Değiştir
reshaped = arr2d.reshape(3, 2)
print("Reshaped:\n", reshaped)  # [[1 2] [3 4] [5 6]]

# 8.2 Flatten/Ravel: Düzleştir
flat = arr2d.flatten()
print("Flatten:", flat)  # [1 2 3 4 5 6]

# 8.3 Stack: Birleştirme
vstack = np.vstack((arr2d, arr2d))  # Dikey
print("Vstack:\n", vstack)

hstack = np.hstack((arr2d, arr2d))  # Yatay
print("Hstack:\n", hstack)

# 8.4 Concatenate
concat = np.concatenate((arr, arr), axis=0)
print("Concat:", concat)  # [1 2 3 4 5 1 2 3 4 5]

# 8.5 Split: Bölme
split = np.split(arr, [2, 4])
print("Split:", split)  # [array([1,2]), array([3,4]), array([5])]

# Bölüm 9: İleri İndeksleme (Boolean, Fancy, Mask)
# Veri filtreleme, selection için güçlü.

# 9.1 Boolean İndeksleme
bool_idx = arr > 3
print("Boolean >3:", arr[bool_idx])  # [4 5]

# 9.2 Fancy Indexing: Belirli İndeksler
fancy = arr[[0, 2, 4]]
print("Fancy:", fancy)  # [1 3 5]

# 9.3 Mask ile Değiştirme
mask = arr % 2 == 0
arr[mask] = -1  # Çiftleri -1 yap
print("Masked Arr:", arr)  # [1 -1 3 -1 5] (orijinal arr değişti, dikkat!)

# Orijinali geri al (örnek için)
arr = np.array([1, 2, 3, 4, 5])

# 9.4 Where: Koşullu Değer Atama
where = np.where(arr > 3, arr, 0)  # >3 ise kendisi, yoksa 0
print("Where:", where)  # [0 0 0 4 5]

# 9.5 Argmax/Argmin: Maks/Min İndeks
print("Argmax:", arr.argmax())  # 4 (indeks)

# Bölüm 10: İleri Konular ve Performans
# Büyük veri için ipuçları.

# 10.1 Copy vs View
view = arr.view()  # Referans, değişiklik arr'ı etkiler
copy = arr.copy()  # Bağımsız kopya
view[0] = 99
print("View Etkisi:", arr)  # [99 2 3 4 5]
arr[0] = 1  # Geri al

# 10.2 Sort
sorted_arr = np.sort(arr)
print("Sorted:", sorted_arr)

# 10.3 Unique Değerler
unique = np.unique(np.array([1,2,2,3]))
print("Unique:", unique)  # [1 2 3]

# 10.4 Broadcasting İleri Örnek
a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])
broadcast_adv = a + b  # 3x1 + 1x3 -> 3x3
print("Adv Broadcast:\n", broadcast_adv)

# 10.5 Memmap: Büyük Dosyalar İçin (Bellek Tasarrufu)
# Örnek: Gerçek dosyada kullan, burada simüle.
# mm = np.memmap('dosya.npy', dtype='float32', mode='w+', shape=(1000,1000))

# Sonuç: Bu script ile NumPy'yi pratik yapın. Veri bilimi projelerinde uygulayın!

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1 1]
 [1 1]
 [1 1]]
Eye Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Empty Array:
 [[0.25 0.5 ]
 [0.75 1.  ]]
arr Shape: (5,)
arr Dtype: int64
arr2d Ndim: 2
arr2d Size: 6
Float Array: [1. 2. 3. 4. 5.]
arr[0]: 1
Slice: [2 3 4]
arr2d[1, 2]: 6
Column Slice: [2 5]
arr[-1]: 5
Step Slice: [1 3 5]
Add 10: [11 12 13 14 15]
Subtract 2: [-1  0  1  2  3]
Multiply 3: [ 3  6  9 12 15]
Divide 2: [0.5 1.  1.5 2.  2.5]
Array Sum: [6 6 6 6 6]
Broadcasting:
 [[2 4 6]
 [5 7 9]]
Power 2: [ 1  4  9 16 25]
Mod 3: [1 2 0 1 2]
Sum: 15
Mean: 3.0
Median: 3.0
Std Dev: 1.4142135623730951
Var: 2.0
Min/Max: 1 5
2D Sum Axis=0 (Sütun): [5 7 9]
2D Mean Axis=1 (Satır): [2. 5.]
Sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Log: [0.69314718 1.09861229 1.38629436 1.6094